#include QMK_KEYBOARD_H
//#include <stdio.h>
//#include <print.h>

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

uint16_t copy_paste_timer;
uint16_t shift_enter_timer;
uint16_t macro_timer;

enum layers {
    _QWERTY = 0,
    _SYMBOLS,
    _NUMBERS,
    _SPACE,
    _FNKEYS,
    _MOUSE,
    _KEEB
};

enum custom_keycodes {
    KC_COPYPASTE = SAFE_RANGE,
    KC_REMENU,
    KC_MACRO,
    KC_RESET_LED
};

#define NUM_REMENUS (7)
enum menustates {
    REM_COLOR = 0,
    REM_MODE,
    REM_REDO,
    REM_ALTTAB,
    REM_MSCROLL,
    REM_PSCROLL,
    REM_VOL,
    REM_HORIZ,
    REM_VERT
};

enum combos {
  FG_TAB = 0,
  JK_ENT
};

#ifdef COMBO_ENABLE
const uint16_t PROGMEM fg_combo[] = {KC_F, KC_G, COMBO_END};
const uint16_t PROGMEM jk_combo[] = {KC_J, KC_K, COMBO_END};

combo_t key_combos[COMBO_COUNT] = {
  [FG_TAB] = COMBO(fg_combo, KC_TAB),
  [JK_ENT] = COMBO(jk_combo, KC_ENT)
};
#endif

#ifndef LEADER_ENABLE
#define KC_LEAD KC_SPC
#endif

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/*
 * Base Layer: QWERTY
 *
 * ,-------------------------------------------.                              ,-------------------------------------------.
 * | ESC    |   Q  |   W  |   E  |   R  |   T  |                              |   Y  |   U  |   I  |   O  |   P  |  | \   |
 * |--------+------+------+------+------+------|                              |------+------+------+------+------+--------|
 * | LSFT   |   A  |   S  |  D   |   F  |   G  |                              |   H  |   J  |   K  |   L  | ;  : |  ' "   |
 * |--------+------+------+------+------+------+-------------.  ,-------------+------+------+------+------+------+--------|
 * | LCTL   |   Z  |   X  |   C  |   V  |   B  | CCCV |      |  | Del  |Leader|   N  |   M  | ,  < | . >  | /  ? |  - _   |
 * `----------------------+------+------+------+------+      |  |------+------+------+------+------+----------------------'
 *                        | GUI  | Alt  |      | Space| Enter|  | Bspc | Space|      | Tab  | AltGr|
 *                        |      |      | Lower| Shift| Alt  |  |      | Nav  | Raise|      |      |
 *                        `----------------------------------'  `----------------------------------'
 */

//*
    [_QWERTY] = LAYOUT(
        KC_GESC, LT(_FNKEYS,KC_Q),    KC_W,  KC_E,     KC_R,    KC_T,                                               KC_Y,    KC_U,    KC_I,    KC_O,   LT(_MOUSE,KC_P),      KC_BSPC,
        KC_TAB , KC_A,   KC_S,  KC_D,     LT(_NUMBERS,KC_F),    KC_G,                                               KC_H,    KC_J,    KC_K,    KC_L,   LT(_SYMBOLS,KC_SCLN),   RGUI_T(KC_QUOT),
        KC_LSFT, LCTL_T(KC_Z), KC_X,  KC_C,  KC_V,     KC_B,    KC_LCTL,  MO(_KEEB),  KC_MACRO,     KC_DEL,  KC_N,  KC_M,    KC_COMM, KC_DOT,  LCTL_T(KC_SLSH), KC_RSFT,
                                      KC_CAPS,  KC_LALT, KC_LGUI, KC_ENT,   KC_GRV,                 KC_LEAD,  LT(_SPACE,KC_SPC), KC_COPYPASTE, KC_CAPS, KC_REMENU

    ),
    [_SYMBOLS] = LAYOUT(
        KC_TRNS,  KC_EXLM,  KC_AT,   KC_LCBR,  KC_RCBR,  KC_PIPE,                                          S(KC_8),  KC_HOME,        KC_PGUP,  KC_END,        KC_TRNS,  KC_BSLS,
        KC_TRNS,  KC_HASH,  KC_DLR,  KC_LPRN,  KC_RPRN,  KC_BSLS,                                          KC_LEFT,  KC_DOWN,        KC_UP,    KC_RGHT,       KC_TRNS,  KC_QUOT,
        KC_LSFT,  KC_PERC,  KC_CIRC, KC_LBRC,  KC_RBRC,  KC_TILD,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_AMPR,  LALT(KC_LEFT),  KC_PGDN,  LALT(KC_RGHT), KC_SLSH,  KC_MINS,
                                     KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_SCLN,  KC_EQL,   KC_EQL,   KC_SPC,  KC_UNDS,  KC_LSCR,        KC_TRNS
        ),
    [_NUMBERS] = LAYOUT(
        KC_TRNS,  KC_EXLM,  KC_AT,   KC_LCBR,  KC_RCBR,  KC_PIPE,                                      KC_PAST, KC_7, KC_8, KC_9, S(KC_EQL), KC_BSPC,
        KC_TRNS,  KC_NO,    KC_DLR,  KC_TAB,  KC_NO,   KC_NO,                                       S(KC_SCLN), KC_4, KC_5, KC_6, KC_MINS, KC_UNDS,
        KC_LSFT,  KC_PERC,  KC_CIRC, KC_LBRC,  KC_RBRC,  KC_TILD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,           KC_NO, KC_1, KC_2, KC_3, KC_EQL, KC_RSFT,
                             KC_TRNS, KC_TRNS, KC_TRNS, LGUI(KC_SPC), KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_LNUM, KC_TRNS
    ),
    [_SPACE] = LAYOUT(
        KC_TRNS,  KC_1,  KC_2,   KC_3,  KC_4,  KC_5,                                                       KC_6, KC_7, KC_8, KC_9, KC_0, KC_DEL,
        KC_TRNS,  KC_HASH,  KC_DLR,  KC_LPRN,  KC_RPRN,  KC_BSLS,                                          KC_NO, KC_ENT, KC_EQL, KC_LBRC, KC_RBRC, KC_PIPE,
        KC_LSFT,  KC_PERC,  KC_CIRC, KC_LBRC,  KC_RBRC,  KC_TILD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,      KC_NO, KC_1, KC_2, KC_3, KC_EQL, KC_ENT,
                             KC_TRNS, KC_TRNS, KC_TRNS, LGUI(KC_SPC), KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_LNUM, KC_TRNS
    ),
    [_FNKEYS] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F7, KC_F8, KC_F9, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F4, KC_F5, KC_F6, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F12, KC_F11, KC_F10, KC_NO),
    [_MOUSE] = LAYOUT(KC_NO, KC_NO, KC_BTN2, KC_MS_U, KC_BTN1, KC_WH_U, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_WH_D, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    [_KEEB] = LAYOUT(
        RESET, RGB_VAI, RGB_SPI, RGB_SAI, RGB_HUI, RGB_TOG,                                KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        DEBUG, RGB_VAD, RGB_SPD, RGB_SAD, RGB_HUD, KC_RESET_LED,                           KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
        RGB_M_T, RGB_M_SN, RGB_M_K, RGB_M_B, RGB_M_P, BL_STEP                                                                                                                                                                                                                                                                                   , KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
                                        KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
    )

//*/
/*
    [_QWERTY] = LAYOUT(
        KC_GESC, LT(_FNKEYS,KC_Q),   KC_W,  KC_E,     KC_R,    KC_T,                                               KC_Y,    KC_U,    KC_I,    KC_O,   LT(4,KC_P),      KC_BSPC,
        KC_TAB , LT(_NUMBERS,KC_A),   KC_S,  KC_D,     KC_F,    KC_G,                                               KC_H,    KC_J,    KC_K,    KC_L,   LT(1,KC_SCLN),   RGUI_T(KC_QUOT),
        KC_LSFT, LCTL_T(KC_Z), KC_X,  KC_C,     KC_V,    KC_B,    KC_LCTL,  MO(_KEEB),   KC_MACRO,   KC_DEL,     KC_N,    KC_M,    KC_COMM, KC_DOT, LCTL_T(KC_SLSH), KC_RSFT,
                                      KC_CAPS,  KC_LALT, KC_LGUI, KC_ENT,   KC_GRV,  KC_LEAD,  LT(_SPACE, KC_SPC), KC_COPYPASTE, KC_CAPS, KC_REMENU

    ),
    [_SYMBOLS] = LAYOUT(
        KC_TRNS,  KC_EXLM,  KC_AT,   KC_LCBR,  KC_RCBR,  KC_PIPE,                                          KC_PAST,  KC_HOME,        KC_PGUP,  KC_END,        KC_TRNS,  KC_BSLS,
        KC_TRNS,  KC_HASH,  KC_DLR,  KC_LPRN,  KC_RPRN,  KC_BSLS,                                          KC_LEFT,  KC_DOWN,        KC_UP,    KC_RGHT,       KC_TRNS,  KC_QUOT,
        KC_LSFT,  KC_PERC,  KC_CIRC, KC_LBRC,  KC_RBRC,  KC_TILD,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_AMPR,  LALT(KC_LEFT),  KC_PGDN,  LALT(KC_RGHT), KC_SLSH,  KC_MINS,
                                     KC_TRNS,  KC_TRNS,  KC_TRNS,  KC_SCLN,  KC_EQL,   KC_EQL,   KC_SCLN,  KC_UNDS,  KC_LSCR,        KC_TRNS
        ),
    [_NUMBERS] = LAYOUT(
        KC_TRNS,  KC_1,  KC_2,   KC_3,  KC_4,  KC_5,                                                       KC_6, KC_7, KC_8, KC_9, KC_0, KC_DEL,
        KC_TRNS,  KC_HASH,  KC_DLR,  KC_LPRN,  KC_RPRN,  KC_BSLS,                                          KC_NO, KC_ENT, KC_EQL, KC_LBRC, KC_RBRC, KC_PIPE,
        KC_LSFT,  KC_PERC,  KC_CIRC, KC_LBRC,  KC_RBRC,  KC_TILD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,      KC_NO, KC_1, KC_2, KC_3, KC_EQL, KC_RSFT,
                             KC_TRNS, KC_TRNS, KC_TRNS, LGUI(KC_SPC), KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_LNUM, KC_TRNS
    ),
    [_SPACE] = LAYOUT(
        KC_TRNS,  KC_1,  KC_2,   KC_3,  KC_4,  KC_5,                                                       KC_6, KC_7, KC_8, KC_9, KC_0, KC_DEL,
        KC_TRNS,  KC_HASH,  KC_DLR,  KC_LPRN,  KC_RPRN,  KC_BSLS,                                          KC_NO, KC_ENT, KC_EQL, KC_LBRC, KC_RBRC, KC_PIPE,
        KC_LSFT,  KC_PERC,  KC_CIRC, KC_LBRC,  KC_RBRC,  KC_TILD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,      KC_NO, KC_1, KC_2, KC_3, KC_EQL, KC_ENT,
                             KC_TRNS, KC_TRNS, KC_TRNS, LGUI(KC_SPC), KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_LNUM, KC_TRNS
    ),
    [_FNKEYS] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F7, KC_F8, KC_F9, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F4, KC_F5, KC_F6, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F1, KC_F2, KC_F3, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F12, KC_F11, KC_F10, KC_NO),
    [_MOUSE] = LAYOUT(KC_NO, KC_NO, KC_BTN2, KC_MS_U, KC_BTN1, KC_WH_U, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_WH_D, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    [_KEEB] = LAYOUT(BL_ON, RGB_VAI, RGB_SPI, RGB_SAI, RGB_HUI, RGB_TOG, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, BL_OFF, RGB_VAD, RGB_SPD, RGB_SAD, RGB_HUD, BL_BRTG, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_M_T, RGB_M_SN, RGB_M_K, RGB_M_B, RGB_M_P, BL_STEP, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
//*/
};

/*
layer_state_t layer_state_set_user(layer_state_t state) {
    return update_tri_layer_state(state, LOWER, RAISE, ADJUST);
}
*/

bool is_recording = false;
bool is_alt_tab_active = false;
bool is_menu_active = false;
uint16_t alt_tab_timer = 0;
int remenu[] = {1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/*
void keyboard_post_init_user(void) {
  // Customise these values to desired behaviour
  debug_enable=true;
  //debug_matrix=true;
  debug_keyboard=true;
  //debug_mouse=true;
}
*/

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    #ifdef CONSOLE_ENABLE
        uprintf("KL: kc: %u, col: %u, row: %u, pressed: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed);
    #endif
    switch (keycode) {
        case KC_COPYPASTE:  // One key copy/paste,
            if (record->event.pressed) {
                copy_paste_timer = timer_read();
            } else {
                if (timer_elapsed(copy_paste_timer) > TAPPING_TERM) {  // Hold, copy
                    tap_code16(LGUI(KC_C));
                } else { // Tap, paste
                    tap_code16(LGUI(KC_V));
                }
            }
            break;
        case KC_MACRO:  // One key macros
            if (record->event.pressed) {
                macro_timer = timer_read();
            } else {
                if (is_recording) {
                    tap_code16(DM_RSTP);
                } else {
                    if (timer_elapsed(macro_timer) > TAPPING_TERM) {  // Hold, record macro
                        tap_code16(DM_REC1);
                    } else { // Tap, play macro
                        tap_code16(DM_PLY1);
                    }
                }
                is_recording = !is_recording;
            }
            return false;
        case KC_REMENU:
            if (record->event.pressed) {
                is_menu_active = !is_menu_active;
            }
            return false;
        case KC_RESET_LED:
            if (record->event.pressed) {
                rgblight_disable();
                rgblight_mode(RGBLIGHT_MODE_STATIC_LIGHT);
                rgblight_sethsv(0, 255, 128);
                rgblight_enable();
            }
            return false;
        }
    return true;
}

#ifdef LEADER_ENABLE
LEADER_EXTERNS();
#endif

void matrix_scan_user(void) {
    if (is_alt_tab_active) {
        if (timer_elapsed(alt_tab_timer) > 1000) {
            unregister_code(KC_LGUI);
            is_alt_tab_active = false;
        }
    }

#ifdef LEADER_ENABLE
    LEADER_DICTIONARY() {
        leading = false;
        leader_end();

        SEQ_ONE_KEY(KC_C) { // Inline Code
            SEND_STRING("`` " SS_TAP(X_LEFT) SS_TAP(X_LEFT));
        }
        SEQ_ONE_KEY(KC_S) {
            SEND_STRING(SS_LGUI(SS_LALT("5")));
        }
        SEQ_ONE_KEY(KC_P) {
            SEND_STRING(SS_LGUI("\\")); // Open 1Password
        }
        SEQ_ONE_KEY(KC_M) {
            SEND_STRING(SS_LGUI(SS_LALT(SS_LSFT(SS_LCTL("M"))))); // Unmute maybe
        }
        SEQ_ONE_KEY(KC_F) {
            SEND_STRING(":)"); // :)
        }
        SEQ_ONE_KEY(KC_D) {
            SEND_STRING(":("); // :(
        }
        SEQ_ONE_KEY(KC_J) {
            SEND_STRING(":thumbsdown:"); // :)
        }
        SEQ_ONE_KEY(KC_K) {
            SEND_STRING(":thumbsup:"); // :(
        }
        SEQ_ONE_KEY(KC_W) {
            SEND_STRING(":aloha:"); // :(
        }
        SEQ_TWO_KEYS(KC_J, KC_J) {
            SEND_STRING("+:thumbsdown:\n"); // :)
        }
        SEQ_TWO_KEYS(KC_K, KC_K) {
            SEND_STRING("+:thumbsup:\n"); // :(
        }
        SEQ_TWO_KEYS(KC_W, KC_W) {
            SEND_STRING("+:aloha:\n"); // :(
        }
        SEQ_TWO_KEYS(KC_P, KC_P) { // Fill or open 1Password
            SEND_STRING(SS_LGUI(SS_LALT("\\")));
        }
        SEQ_TWO_KEYS(KC_M, KC_M) {  // Send MIDI Note
            tap_code16(MI_C_1);
        }
        SEQ_TWO_KEYS(KC_M, KC_COMMA) {  // Send MIDI Note
            tap_code16(MI_D_1);
        }
        SEQ_TWO_KEYS(KC_M, KC_DOT) {  // Send MIDI Note
            tap_code16(MI_E_1);
        }
        SEQ_ONE_KEY(KC_H) {  //¯\_(ツ)_/¯
            #ifdef UNICODE_ENABLE
            send_unicode_string("¯\\_(ツ)_/¯");
            #else
            SEND_STRING(SS_LALT("00af") "\\_(" SS_LALT("30c4") ")_/" SS_LALT("00af"));
            #endif
        }
        SEQ_TWO_KEYS(KC_T, KC_F) {
            #ifdef UNICODE_ENABLE
            send_unicode_string("(╯°□°)╯︵  ┻━┻");
            #else
            SEND_STRING("(" SS_LALT("232B") SS_LALT("00B0") SS_LALT("25A1") SS_LALT("00B0")  ")" "╯︵  ┻━┻");
            #endif
        }
        SEQ_THREE_KEYS(KC_D, KC_T, KC_F) {
            #ifdef UNICODE_ENABLE
            send_unicode_string("┻━┻ ︵ヽ(°□°)ﾉ︵ ┻━┻");
            #else
            #endif
        }
        SEQ_TWO_KEYS(KC_C, KC_C) { // Code block
            SEND_STRING("```" SS_LSFT("\n\n") "```" SS_TAP(X_UP));
        }
    }
#endif
}


#ifdef OLED_DRIVER_ENABLE
oled_rotation_t oled_init_user(oled_rotation_t rotation) {
	return OLED_ROTATION_180;
}

static void render_qmk_logo(void) {
    /*static const char PROGMEM qmk_logo[] = {
        0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8a,0x8b,0x8c,0x8d,0x8e,0x8f,0x90,0x91,0x92,0x93,0x94,
        0xa0,0xa1,0xa2,0xa3,0xa4,0xa5,0xa6,0xa7,0xa8,0xa9,0xaa,0xab,0xac,0xad,0xae,0xaf,0xb0,0xb1,0xb2,0xb3,0xb4,
        0xc0,0xc1,0xc2,0xc3,0xc4,0xc5,0xc6,0xc7,0xc8,0xc9,0xca,0xcb,0xcc,0xcd,0xce,0xcf,0xd0,0xd1,0xd2,0xd3,0xd4,0
    };*/

    //oled_write_P(qmk_logo, false);
}

static void render_kyria_logo(void) {
    /*
    static const char PROGMEM kyria_logo[] = {
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,128,128,192,224,240,112,120, 56, 60, 28, 30, 14, 14, 14,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7, 14, 14, 14, 30, 28, 60, 56,120,112,240,224,192,128,128,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,192,224,240,124, 62, 31, 15,  7,  3,  1,128,192,224,240,120, 56, 60, 28, 30, 14, 14,  7,  7,135,231,127, 31,255,255, 31,127,231,135,  7,  7, 14, 14, 30, 28, 60, 56,120,240,224,192,128,  1,  3,  7, 15, 31, 62,124,240,224,192,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,240,252,255, 31,  7,  1,  0,  0,192,240,252,254,255,247,243,177,176, 48, 48, 48, 48, 48, 48, 48,120,254,135,  1,  0,  0,255,255,  0,  0,  1,135,254,120, 48, 48, 48, 48, 48, 48, 48,176,177,243,247,255,254,252,240,192,  0,  0,  1,  7, 31,255,252,240,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,255,255,255,  0,  0,  0,  0,  0,254,255,255,  1,  1,  7, 30,120,225,129,131,131,134,134,140,140,152,152,177,183,254,248,224,255,255,224,248,254,183,177,152,152,140,140,134,134,131,131,129,225,120, 30,  7,  1,  1,255,255,254,  0,  0,  0,  0,  0,255,255,255,  0,  0,  0,  0,255,255,  0,  0,192,192, 48, 48,  0,  0,240,240,  0,  0,  0,  0,  0,  0,240,240,  0,  0,240,240,192,192, 48, 48, 48, 48,192,192,  0,  0, 48, 48,243,243,  0,  0,  0,  0,  0,  0, 48, 48, 48, 48, 48, 48,192,192,  0,  0,  0,  0,  0,
        0,  0,  0,255,255,255,  0,  0,  0,  0,  0,127,255,255,128,128,224,120, 30,135,129,193,193, 97, 97, 49, 49, 25, 25,141,237,127, 31,  7,255,255,  7, 31,127,237,141, 25, 25, 49, 49, 97, 97,193,193,129,135, 30,120,224,128,128,255,255,127,  0,  0,  0,  0,  0,255,255,255,  0,  0,  0,  0, 63, 63,  3,  3, 12, 12, 48, 48,  0,  0,  0,  0, 51, 51, 51, 51, 51, 51, 15, 15,  0,  0, 63, 63,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 48, 48, 63, 63, 48, 48,  0,  0, 12, 12, 51, 51, 51, 51, 51, 51, 63, 63,  0,  0,  0,  0,  0,
        0,  0,  0,  0, 15, 63,255,248,224,128,  0,  0,  3, 15, 63,127,255,239,207,141, 13, 12, 12, 12, 12, 12, 12, 12, 30,127,225,128,  0,  0,255,255,  0,  0,128,225,127, 30, 12, 12, 12, 12, 12, 12, 12, 13,141,207,239,255,127, 63, 15,  3,  0,  0,128,224,248,255, 63, 15,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  3,  7, 15, 62,124,248,240,224,192,128,  1,  3,  7, 15, 30, 28, 60, 56,120,112,112,224,224,225,231,254,248,255,255,248,254,231,225,224,224,112,112,120, 56, 60, 28, 30, 15,  7,  3,  1,128,192,224,240,248,124, 62, 15,  7,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  3,  7, 15, 14, 30, 28, 60, 56,120,112,112,112,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,112,112,112,120, 56, 60, 28, 30, 14, 15,  7,  3,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
    };
    oled_write_raw_P(kyria_logo, sizeof(kyria_logo));
    */
    render_qmk_logo();
    oled_write_P(PSTR("     Kyria:Ringmaster\n"), false);
}

static void menu_name(int menu) {
    switch(menu) {
        case REM_COLOR: oled_write_P(PSTR(" color "), false); break;
        case REM_MODE: oled_write_P(PSTR(" mode  "), false); break;
        case REM_REDO: oled_write_P(PSTR("re/undo"), false); break;
        case REM_ALTTAB: oled_write_P(PSTR("alt-tab"), false); break;
        case REM_MSCROLL: oled_write_P(PSTR("mscroll"), false); break;
        case REM_VOL: oled_write_P(PSTR("volume "), false); break;
        case REM_PSCROLL: oled_write_P(PSTR("pscroll"), false); break;
        case REM_HORIZ: oled_write_P(PSTR(" horiz "), false); break;
        case REM_VERT: oled_write_P(PSTR(" vert  "), false); break;
        default: oled_write_P(PSTR(" -none-"), false); break;
    }
}

extern rgblight_config_t rgblight_config;

static void render_status(void) {
    // QMK Logo and version information
    render_qmk_logo();
    oled_write_P(PSTR("     Kyria:Ringmaster\n"), false);

    menu_name(remenu[0 + 2 * get_highest_layer(layer_state)]);
    if (is_menu_active) {
        oled_write_P(PSTR(" <--> "), false);
    } else {
        oled_write_P(PSTR("      "), false);
    }
    menu_name(remenu[1 + 2 * get_highest_layer(layer_state)]);
    oled_write_P(PSTR("\n"), false);


    // Host Keyboard Layer Status
    oled_write_P(PSTR("Layer: "), false);

    switch (get_highest_layer(layer_state)) {
        case _QWERTY:
            oled_write_P(PSTR("Default\n"), false);
            break;
        case _SYMBOLS:
            oled_write_P(PSTR("Symbols\n"), false);
            break;
        case _FNKEYS:
            oled_write_P(PSTR("FnKeys\n"), false);
            break;
        case _NUMBERS:
            oled_write_P(PSTR("Numbers\n"), false);
            break;
        case _SPACE:
            oled_write_P(PSTR("Space\n"), false);
            break;
        case _MOUSE:
            oled_write_P(PSTR("Mouse\n"), false);
            break;
        default:
            oled_write_P(PSTR("Lighting\n"), false);
    }

    // Host Keyboard LED Status
    led_t led_state = host_keyboard_led_state();
    oled_write_P(led_state.num_lock    ? PSTR("NUMLCK ") : PSTR("       "), false);
    oled_write_P(led_state.caps_lock   ? PSTR("CAPLCK ") : PSTR("       "), false);
    oled_write_P(led_state.scroll_lock ? PSTR("SCRLCK ") : PSTR("       "), false);

    /*
    static char led_buf[50];

    snprintf(led_buf, sizeof(led_buf) - 1, "RGB:%cM: %2d\nh: %2ds: %2dv: %2d\nS: %2d\n",
                rgblight_config.enable ? '*' : '.', (uint8_t)rgblight_config.mode,
                (uint8_t)(rgblight_config.hue / RGBLIGHT_HUE_STEP),
                (uint8_t)(rgblight_config.sat / RGBLIGHT_SAT_STEP),
                (uint8_t)(rgblight_config.val / RGBLIGHT_VAL_STEP),
                (uint8_t)rgblight_get_speed());
            oled_write(led_buf, false);
            //*/
}

void oled_task_user(void) {
    if (is_keyboard_master()) {
        render_status(); // Renders the current keyboard state (layer, lock, caps, scroll, etc)
    } else {
        render_kyria_logo();
    }
}
#endif

#ifdef ENCODER_ENABLE
void encoder_update_user(uint8_t index, bool clockwise) {
    bool real_clockwise = index == 0 ? !clockwise : clockwise;

    if (is_menu_active) {
        if (real_clockwise) {
            remenu[index  + 2 * get_highest_layer(layer_state)]--;
        } else {
            remenu[index  + 2 * get_highest_layer(layer_state)]++;
        }
        if (remenu[index  + 2 * get_highest_layer(layer_state)] < 0) {
            remenu[index  + 2 * get_highest_layer(layer_state)] = NUM_REMENUS - 1;
        }
        if (remenu[index  + 2 * get_highest_layer(layer_state)] >= NUM_REMENUS) {
            remenu[index  + 2 * get_highest_layer(layer_state)] = 0;
        }
    }
    else {
        switch (remenu[index  + 2 * get_highest_layer(layer_state)]) {
            case REM_COLOR:
                if (real_clockwise) {
                    rgblight_increase_hue();
                } else {
                    rgblight_decrease_hue();
                }
                break;
            case REM_MODE:
                if (real_clockwise) {
                    rgblight_step_noeeprom();
                } else {
                    rgblight_step_reverse_noeeprom();
                }
                break;
            case REM_REDO:
                if (real_clockwise) {
                    tap_code16(G(KC_Z));
                } else {
                    tap_code16(S(G(KC_Z)));
                }
                break;
            case REM_ALTTAB:
                alt_tab_timer = timer_read();
                if (!is_alt_tab_active) {
                    is_alt_tab_active = true;
                    register_code(KC_LGUI);
                }
                if (real_clockwise) {
                    tap_code16(S(KC_TAB));
                } else {
                    tap_code16(KC_TAB);
                }
                break;
            case REM_MSCROLL:
                // Scrolling with Mouse wheel
                if (real_clockwise) {
                    tap_code(KC_WH_U);
                } else {
                    tap_code(KC_WH_D);
                }
                break;
            case REM_VOL:
                // Volume control.
                if (real_clockwise) {
                    tap_code(KC_VOLU);
                } else {
                    tap_code(KC_VOLD);
                }
                break;
            case REM_PSCROLL:
                // Scroll by pgup/dn.
                if (real_clockwise) {
                    tap_code(KC_PGDN);
                } else {
                    tap_code(KC_PGUP);
                }
                break;
            case REM_HORIZ:
                // Horizontal arrows
                if (real_clockwise) {
                    tap_code(KC_LEFT);
                } else {
                    tap_code(KC_RIGHT);
                }
                break;
            case REM_VERT:
                // Vertical arrows
                if (real_clockwise) {
                    tap_code(KC_UP);
                } else {
                    tap_code(KC_DOWN);
                }
                break;
        }
    }
}
#endif
