OLED_DRIVER_ENABLE = yes   # Enables the use of OLED displays
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
RGB_MATRIX_ENABLE = no
LEADER_ENABLE = yes        # Enable the Leader Key feature
MOUSEKEY_ENABLE = yes
#CONSOLE_ENABLE = yes
EXTRAFLAGS += -flto
#UNICODE_ENABLE = yes
#DYNAMIC_MACRO_ENABLE = yes
#MIDI_ENABLE = yes
#TAP_DANCE_ENABLE = yes
#KEY_LOCK_ENABLE = yes
COMBO_ENABLE = yes
